# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-travel2-service
  datasource:
    url: jdbc:mysql://${TRAVEL2_MYSQL_HOST:ts-travel2-mysql}:${TRAVEL2_MYSQL_PORT:3306}/${TRAVEL2_MYSQL_DATABASE:ts-travel2-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${TRAVEL2_MYSQL_USER:root}
    password: ${TRAVEL2_MYSQL_PASSWORD:Abcd1234#}

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: travel2.controller
