services:
  nacos:
    image: nacos/nacos-server
    ports:
      - 8848:8848
      - 9848:9848
    networks:
      - my-network
    env_file:
      - env/nacos-standalone.env
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      interval: 1m
      start_period: 30s

  rabbitmq:
    restart: always
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - my-network

  mysql:
    build: mysql
    image: ${IMG_REPO}/mysql
    restart: always
    env_file:
      - env/ts-mysql.env
    networks:
      - my-network
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "${MYSQL_AUTH_USER}", "-p${MYSQL_AUTH_PASSWORD}" ]
      interval: 1m
      start_period: 30s

  ts-ui-dashboard:
    build: ts-ui-dashboard
    image: ${IMG_REPO}/ts-ui-dashboard:${IMG_TAG}
    restart: always
    depends_on:
      - ts-gateway-service
    ports:
      - 8080:8080
    networks:
      - my-network

  ts-auth-service:
    build: ts-auth-service
    image: ${IMG_REPO}/ts-auth-service:${IMG_TAG}
    restart: always
    environment:
      AUTH_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12340:12340
    networks:
      - my-network

  ts-user-service:
    build: ts-user-service
    image: ${IMG_REPO}/ts-user-service:${IMG_TAG}
    restart: always
    environment:
      USER_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12342:12342
    networks:
      - my-network

  ts-verification-code-service:
    build: ts-verification-code-service
    image: ${IMG_REPO}/ts-verification-code-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 15678:15678
    networks:
      - my-network

  ts-route-service:
    build: ts-route-service
    image: ${IMG_REPO}/ts-route-service:${IMG_TAG}
    restart: always
    environment:
      ROUTE_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 11178:11178
    networks:
      - my-network

  ts-contacts-service:
    build: ts-contacts-service
    image: ${IMG_REPO}/ts-contacts-service:${IMG_TAG}
    restart: always
    environment:
      CONTACTS_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12347:12347
    networks:
      - my-network


  ts-order-service:
    build: ts-order-service
    image: ${IMG_REPO}/ts-order-service:${IMG_TAG}
    restart: always
    environment:
      ORDER_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12031:12031
    networks:
      - my-network

  ts-order-other-service:
    build: ts-order-other-service
    image: ${IMG_REPO}/ts-order-other-service:${IMG_TAG}
    restart: always
    environment:
      ORDER_OTHER_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12032:12032
    networks:
      - my-network

  ts-config-service:
    build: ts-config-service
    image: ${IMG_REPO}/ts-config-service:${IMG_TAG}
    restart: always
    environment:
      CONFIG_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 15679:15679
    networks:
      - my-network

  ts-station-service:
    build: ts-station-service
    image: ${IMG_REPO}/ts-station-service:${IMG_TAG}
    restart: always
    environment:
      STATION_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-train-service:
    build: ts-train-service
    image: ${IMG_REPO}/ts-train-service:${IMG_TAG}
    restart: always
    environment:
      TRAIN_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 14567:14567
    networks:
      - my-network

  ts-travel-service:
    build: ts-travel-service
    image: ${IMG_REPO}/ts-travel-service:${IMG_TAG}
    restart: always
    environment:
      TRAVEL_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel2-service:
    build: ts-travel2-service
    image: ${IMG_REPO}/ts-travel2-service:${IMG_TAG}
    restart: always
    environment:
      TRAVEL2_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 16346:16346
    networks:
      - my-network

  ts-preserve-service:
    build: ts-preserve-service
    image: ${IMG_REPO}/ts-preserve-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - 14568:14568
    networks:
      - my-network

  ts-preserve-other-service:
    build: ts-preserve-other-service
    image: ${IMG_REPO}/ts-preserve-other-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - 14569:14569
    networks:
      - my-network

  ts-basic-service:
    build: ts-basic-service
    image: ${IMG_REPO}/ts-basic-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 15680:15680
    networks:
        - my-network

  ts-price-service:
    build: ts-price-service
    image: ${IMG_REPO}/ts-price-service:${IMG_TAG}
    restart: always
    environment:
      PRICE_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 16579:16579
    networks:
      - my-network

  ts-notification-service:
    build: ts-notification-service
    image: ${IMG_REPO}/ts-notification-service:${IMG_TAG}
    restart: always
    environment:
      NOTIFICATION_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - 17853:17853
    networks:
      - my-network


  ts-security-service:
    build: ts-security-service
    image: ${IMG_REPO}/ts-security-service:${IMG_TAG}
    restart: always
    environment:
      SECURITY_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 11188:11188
    networks:
      - my-network


  ts-inside-payment-service:
    build: ts-inside-payment-service
    image: ${IMG_REPO}/ts-inside-payment-service:${IMG_TAG}
    restart: always
    environment:
      INSIDE_PAYMENT_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 18673:18673
    networks:
      - my-network

  ts-execute-service:
    build: ts-execute-service
    image: ${IMG_REPO}/ts-execute-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 12386:12386
    networks:
      - my-network

  ts-payment-service:
    build: ts-payment-service
    image: ${IMG_REPO}/ts-payment-service:${IMG_TAG}
    restart: always
    environment:
      PAYMENT_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 19001:19001
    networks:
      - my-network

  ts-rebook-service:
    build: ts-rebook-service
    image: ${IMG_REPO}/ts-rebook-service:${IMG_TAG}
    restart: always
    environment:
      REBOOK_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 18886:18886
    networks:
      - my-network

  ts-cancel-service:
    build: ts-cancel-service
    image: ${IMG_REPO}/ts-cancel-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 18885:18885
    networks:
      - my-network

  ts-assurance-service:
    build: ts-assurance-service
    image: ${IMG_REPO}/ts-assurance-service:${IMG_TAG}
    restart: always
    environment:
      ASSURANCE_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 18889:18888 # Mapping to a different port to avoid conflict with ts-gateway-service
    networks:
      - my-network

  ts-seat-service:
    build: ts-seat-service
    image: ${IMG_REPO}/ts-seat-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 18898:18898
    networks:
      - my-network

  ts-travel-plan-service:
    build: ts-travel-plan-service
    image: ${IMG_REPO}/ts-travel-plan-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 14322:14322
    networks:
      - my-network

  ts-news-service:
    build: ts-news-service
    image: ${IMG_REPO}/ts-news-service:${IMG_TAG}
    restart: always
    ports:
      - 12862:12862
    networks:
      - my-network

  ts-voucher-service:
    build: ts-voucher-service
    image: ${IMG_REPO}/ts-voucher-service:${IMG_TAG}
    restart: always
    environment:
      VOUCHER_MYSQL_HOST: mysql
    ports:
      - 16101:16101
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  ts-route-plan-service:
    build: ts-route-plan-service
    image: ${IMG_REPO}/ts-route-plan-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 14578:14578
    networks:
      - my-network

  ts-food-service:
    build: ts-food-service
    image: ${IMG_REPO}/ts-food-service:${IMG_TAG}
    restart: always
    environment:
      FOOD_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - my-network

  ts-consign-service:
    build: ts-consign-service
    image: ${IMG_REPO}/ts-consign-service:${IMG_TAG}
    restart: always
    environment:
      CONSIGN_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 16111:16111
    networks:
      - my-network

  ts-consign-price-service:
    build: ts-consign-price-service
    image: ${IMG_REPO}/ts-consign-price-service:${IMG_TAG}
    restart: always
    environment:
      CONSIGN_PRICE_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 16110:16110
    networks:
      - my-network

  ts-admin-basic-info-service:
    build: ts-admin-basic-info-service
    image: ${IMG_REPO}/ts-admin-basic-info-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 18767:18767
    networks:
      - my-network

  ts-admin-order-service:
    build: ts-admin-order-service
    image: ${IMG_REPO}/ts-admin-order-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 16112:16112
    networks:
      - my-network

  ts-admin-route-service:
    build: ts-admin-route-service
    image: ${IMG_REPO}/ts-admin-route-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 16113:16113
    networks:
      - my-network

  ts-admin-travel-service:
    build: ts-admin-travel-service
    image: ${IMG_REPO}/ts-admin-travel-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 16114:16114
    networks:
      - my-network

  ts-admin-user-service:
    build: ts-admin-user-service
    image: ${IMG_REPO}/ts-admin-user-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    networks:
      - my-network

  ts-avatar-service:
    build: ts-avatar-service
    image: ${IMG_REPO}/ts-avatar-service:${IMG_TAG}
    restart: always
    ports:
      - 17001:17001
    networks:
      - my-network

  ts-delivery-service:
    build: ts-delivery-service
    image: ${IMG_REPO}/ts-delivery-service:${IMG_TAG}
    restart: always
    environment:
      DELIVERY_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - 18808:18808
    networks:
      - my-network

  ts-food-delivery-service:
    build: ts-food-delivery-service
    image: ${IMG_REPO}/ts-food-delivery-service:${IMG_TAG}
    restart: always
    environment:
      FOOD_DELIVERY_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 18957:18957
    networks:
      - my-network

  ts-gateway-service:
    build: ts-gateway-service
    image: ${IMG_REPO}/ts-gateway-service:${IMG_TAG}
    restart: always
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - 18888:18888
    networks:
      - my-network

  ts-station-food-service:
    build: ts-station-food-service
    image: ${IMG_REPO}/ts-station-food-service:${IMG_TAG}
    restart: always
    environment:
      STATION_FOOD_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 18855:18855
    networks:
      - my-network

  ts-train-food-service:
    build: ts-train-food-service
    image: ${IMG_REPO}/ts-train-food-service:${IMG_TAG}
    restart: always
    environment:
      TRAIN_FOOD_MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy
    ports:
      - 19999:19999
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge
