server:
  port: 16114

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller