spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-config-service
  datasource:
    url: jdbc:mysql://${CONFIG_MYSQL_HOST:ts-config-mysql}:${CONFIG_MYSQL_PORT:3306}/${CONFIG_MYSQL_DATABASE:ts-config-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${CONFIG_MYSQL_USER:root}
    password: ${CONFIG_MYSQL_PASSWORD:Abcd1234#}
  jpa:
    hibernate:
      ddl-auto: update


# HTTP Server
server:
  port: 15679  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller