# HTTP Server
server:
  port: 18888  # HTTP (Tomcat) port

spring:
  main:
    web-application-type: reactive
  application:
    name: ts-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
        fail-fast: false

    gateway:
      routes:
        - id: admin-basic-info
          uri: http://${ADMIN_BASIC_INFO_SERVICE_HOST:ts-admin-basic-info-service}:${ADMIN_BASIC_INFO_SERVICE_PORT:18767}
          predicates:
            - Path=/api/v1/adminbasicservice/**

        - id: admin-order
          uri: http://${ADMIN_ORDER_SERVICE_HOST:ts-admin-order-service}:${ADMIN_ORDER_SERVICE_PORT:16112}
          predicates:
            - Path=/api/v1/adminorderservice/**

        - id: admin-route
          uri: http://${ADMIN_ROUTE_SERVICE_HOST:ts-admin-route-service}:${ADMIN_ROUTE_SERVICE_PORT:16113}
          predicates:
            - Path=/api/v1/adminrouteservice/**

        - id: admin-travel
          uri: http://${ADMIN_TRAVEL_SERVICE_HOST:ts-admin-travel-service}:${ADMIN_TRAVEL_SERVICE_PORT:16114}
          predicates:
            - Path=/api/v1/admintravelservice/**

        - id: admin-user
          uri: http://${ADMIN_USER_SERVICE_HOST:ts-admin-user-service}:${ADMIN_USER_SERVICE_PORT:16115}
          predicates:
            - Path=/api/v1/adminuserservice/users/**

        - id: assurance
          uri: http://${ASSURANCE_SERVICE_HOST:ts-assurance-service}:${ASSURANCE_SERVICE_PORT:18888}
          predicates:
            - Path=/api/v1/assuranceservice/**

        - id: auth
          uri: http://${AUTH_SERVICE_HOST:ts-auth-service}:${AUTH_SERVICE_PORT:12340}
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-user
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}:${AUTH_SERVICE_PORT:12340}
          predicates:
            - Path=/api/v1/users/**

        - id: avatar
          uri: http://${AVATAR_SERVICE_HOST:ts-avatar-service}:${AVATAR_SERVICE_PORT:17001}
          predicates:
            - Path=/api/v1/avatar/**

        - id: basic
          uri: http://${BASIC_SERVICE_HOST:ts-basic-service}:${BASIC_SERVICE_PORT:15680}
          predicates:
            - Path=/api/v1/basicservice/**

        - id: cancel
          uri: http://${CANCEL_SERVICE_HOST:ts-cancel-service}:${CANCEL_SERVICE_PORT:18885}
          predicates:
            - Path=/api/v1/cancelservice/**

        - id: config
          uri: http://${CONFIG_SERVICE_HOST:ts-config-service}:${CONFIG_SERVICE_PORT:15679}
          predicates:
            - Path=/api/v1/configservice/**

        - id: consign-price
          uri: http://${CONSIGN_PRICE_SERVICE_HOST:ts-consign-price-service}:${CONSIGN_PRICE_SERVICE_PORT:16110}
          predicates:
            - Path=/api/v1/consignpriceservice/**

        - id: consign
          uri: http://${CONSIGN_SERVICE_HOST:ts-consign-service}:${CONSIGN_SERVICE_PORT:16111}
          predicates:
            - Path=/api/v1/consignservice/**

        - id: contacts
          uri: http://${CONTACTS_SERVICE_HOST:ts-contacts-service}:${CONTACTS_SERVICE_PORT:12347}
          predicates:
            - Path=/api/v1/contactservice/**

        - id: execute
          uri: http://${EXECUTE_SERVICE_HOST:ts-execute-service}:${EXECUTE_SERVICE_PORT:12386}
          predicates:
            - Path=/api/v1/executeservice/**

        - id: food
          uri: http://${FOOD_SERVICE_HOST:ts-food-service}:${FOOD_SERVICE_PORT:18856}
          predicates:
            - Path=/api/v1/foodservice/**

        - id: inside-payment
          uri: http://${INSIDE_PAYMENT_SERVICE_HOST:ts-inside-payment-service}:${INSIDE_PAYMENT_SERVICE_PORT:18673}
          predicates:
            - Path=/api/v1/inside_pay_service/**

        - id: notification
          uri: http://${NOTIFICATION_SERVICE_HOST:ts-notification-service}:${NOTIFICATION_SERVICE_PORT:17853}
          predicates:
            - Path=/api/v1/notifyservice/**

        - id: order-other
          uri: http://${ORDER_OTHER_SERVICE_HOST:ts-order-other-service}:${ORDER_OTHER_SERVICE_PORT:12032}
          predicates:
            - Path=/api/v1/orderOtherService/**

        - id: order
          uri: http://${ORDER_SERVICE_HOST:ts-order-service}:${ORDER_SERVICE_PORT:12031}
          predicates:
            - Path=/api/v1/orderservice/**

        - id: payment
          uri: http://${PAYMENT_SERVICE_HOST:ts-payment-service}:${PAYMENT_SERVICE_PORT:19001}
          predicates:
            - Path=/api/v1/paymentservice/**

        - id: preserve-other
          uri: http://${PRESERVE_OTHER_SERVICE_HOST:ts-preserve-other-service}:${PRESERVE_OTHER_SERVICE_PORT:14569}
          predicates:
            - Path=/api/v1/preserveotherservice/**

        - id: preserve
          uri: http://${PRESERVE_SERVICE_HOST:ts-preserve-service}:${PRESERVE_SERVICE_PORT:14568}
          predicates:
            - Path=/api/v1/preserveservice/**

        - id: price
          uri: http://${PRICE_SERVICE_HOST:ts-price-service}:${PRICE_SERVICE_PORT:16579}
          predicates:
            - Path=/api/v1/priceservice/**

        - id: rebook
          uri: http://${REBOOK_SERVICE_HOST:ts-rebook-service}:${REBOOK_SERVICE_PORT:18886}
          predicates:
            - Path=/api/v1/rebookservice/**

        - id: route-plan
          uri: http://${ROUTE_PLAN_SERVICE_HOST:ts-route-plan-service}:${ROUTE_PLAN_SERVICE_PORT:14578}
          predicates:
            - Path=/api/v1/routeplanservice/**

        - id: route
          uri: http://${ROUTE_SERVICE_HOST:ts-route-service}:${ROUTE_SERVICE_PORT:11178}
          predicates:
            - Path=/api/v1/routeservice/**

        - id: seat
          uri: http://${SEAT_SERVICE_HOST:ts-seat-service}:${SEAT_SERVICE_PORT:18898}
          predicates:
            - Path=/api/v1/seatservice/**

        - id: security
          uri: http://${SECURITY_SERVICE_HOST:ts-security-service}:${SECURITY_SERVICE_PORT:11188}
          predicates:
            - Path=/api/v1/securityservice/**

        - id: station-food
          uri: http://${STATION_FOOD_SERVICE_HOST:ts-station-food-service}:${STATION_FOOD_SERVICE_PORT:18855}
          predicates:
            - Path=/api/v1/stationfoodservice/**

        - id: station
          uri: http://${STATION_SERVICE_HOST:ts-station-service}:${STATION_SERVICE_PORT:12345}
          predicates:
            - Path=/api/v1/stationservice/**

        - id: train-food
          uri: http://${TRAIN_FOOD_SERVICE_HOST:ts-train-food-service}:${TRAIN_FOOD_SERVICE_PORT:19999}
          predicates:
            - Path=/api/v1/trainfoodservice/**

        - id: train
          uri: http://${TRAIN_SERVICE_HOST:ts-train-service}:${TRAIN_SERVICE_PORT:14567}
          predicates:
            - Path=/api/v1/trainservice/**

        - id: travel2
          uri: http://${TRAVEL2_SERVICE_HOST:ts-travel2-service}:${TRAVEL2_SERVICE_PORT:16346}
          predicates:
            - Path=/api/v1/travel2service/**

        - id: travel-plan
          uri: http://${TRAVEL_PLAN_SERVICE_HOST:ts-travel-plan-service}:${TRAVEL_PLAN_SERVICE_PORT:14322}
          predicates:
            - Path=/api/v1/travelplanservice/**

        - id: travel
          uri: http://${TRAVEL_SERVICE_HOST:ts-travel-service}:${TRAVEL_SERVICE_PORT:12346}
          predicates:
            - Path=/api/v1/travelservice/**

        - id: user
          uri: http://${USER_SERVICE_HOST:ts-user-service}:${USER_SERVICE_PORT:12342}
          predicates:
            - Path=/api/v1/userservice/users/**

        - id: verification-code
          uri: http://${VERIFICATION_CODE_SERVICE_HOST:ts-verification-code-service}
          predicates:
            - Path=/api/v1/verifycode/**
