spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-price-service
  datasource:
    url: jdbc:mysql://${PRICE_MYSQL_HOST:ts-price-mysql}:${PRICE_MYSQL_PORT:3306}/${PRICE_MYSQL_DATABASE:ts-price-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${PRICE_MYSQL_USER:root}
    password: ${PRICE_MYSQL_PASSWORD:Abcd1234#}
  jpa:
    hibernate:
      ddl-auto: update


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller