spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-route-service
  datasource:
    url: jdbc:mysql://${ROUTE_MYSQL_HOST:ts-route-mysql}:${ROUTE_MYSQL_PORT:3306}/${ROUTE_MYSQL_DATABASE:ts-route-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${ROUTE_MYSQL_USER:root}
    password: ${ROUTE_MYSQL_PASSWORD:Abcd1234#}
  jpa:
    hibernate:
      ddl-auto: update

# HTTP Server
server:
  port: 11178  # HTTP (Tomcat) port

swagger:
  controllerPackage: route.controller