server:
  port: 18885  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller
