server:
  port: 19999

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-train-food-service
  datasource:
    url: jdbc:mysql://${TRAIN_FOOD_MYSQL_HOST:ts-train-food-mysql}:${TRAIN_FOOD_MYSQL_PORT:3306}/${TRAIN_FOOD_MYSQL_DATABASE:ts-train-food-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${TRAIN_FOOD_MYSQL_USER:root}
    password: ${TRAIN_FOOD_MYSQL_PASSWORD:Abcd1234#}

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: trainFood.controller