server:
  port: 15680

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.microservice.controller