# HTTP Server
server:
  port: 17525  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-wait-order-service
  datasource:
    url: jdbc:mysql://${WAIT_ORDER_MYSQL_HOST:10.176.122.1}:${WAIT_ORDER_MYSQL_PORT:3306}/${WAIT_ORDER_MYSQL_DATABASE:ts}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${WAIT_ORDER_MYSQL_USER:root}
    password: ${WAIT_ORDER_MYSQL_PASSWORD:Abcd1234#}
  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: waitorder.controller