server:
  port: 18673

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-inside-payment-service

  datasource:
    url: jdbc:mysql://${INSIDE_PAYMENT_MYSQL_HOST:ts-inside-payment-mysql}:${INSIDE_PAYMENT_MYSQL_PORT:3306}/${INSIDE_PAYMENT_MYSQL_DATABASE:ts-inside-payment-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${INSIDE_PAYMENT_MYSQL_USER:root}
    password: ${INSIDE_PAYMENT_MYSQL_PASSWORD:Abcd1234#}
  jpa:
    hibernate:
      ddl-auto: update


swagger:
  controllerPackage: inside_payment.controller
