server:
  port: 18855

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos}
  application:
    name: ts-station-food-service
  datasource:
    url: jdbc:mysql://${STATION_FOOD_MYSQL_HOST:ts-station-food-mysql}:${STATION_FOOD_MYSQL_PORT:3306}/${STATION_FOOD_MYSQL_DATABASE:ts-station-food-mysql}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${STATION_FOOD_MYSQL_USER:root}
    password: ${STATION_FOOD_MYSQL_PASSWORD:Abcd1234#}

  jpa:
    hibernate:
      ddl-auto: update


swagger:
  controllerPackage: food.controller